GLUON_MULTIDOMAIN=1

DEFAULT_GLUON_RELEASE := 2023.2.3at$(shell date '+%Y%m%d')i

GLUON_RELEASE ?= $(DEFAULT_GLUON_RELEASE)
GLUON_PRIORITY ?= 0
GLUON_REGION ?= eu
GLUON_LANGS ?= en de
GLUON_BRANCH ?= stable
